# Site settings
title:  学习日志
email: fsderg@gmail.com
description: "Write the code, Change the world.<br>用程序书写人生"
baseurl: ""
url: "http://blog.fsder.com"
twitter_username: fsderg
github_username:  fsder

# Build settings
# markdown: kramdown
permalink: pretty
markdown: redcarpet
# pygments: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]


# Author details.
authors:
    fsder:
        name: fsder
        email: fsderg@gmail.com
        web: fsder.com

    James:
        name: JamesLee
        email: lgy@live.com
