# Site settings
title: Full Stack Developer
email: fsderg@gmail.com
description: "Write the code, Change the world."
baseurl: ""
url: "http://blog.fsder.com"
# twitter_username: jekyllrb
github_username:  fsder

# Build settings
# markdown: kramdown
permalink: pretty
markdown: redcarpet
pygments: true
# redcarpet:
#     extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
